apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/part-of: code-with-quarkus-dev-files-mvn
  name: code-with-quarkus-dev-filksrg
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: code-with-quarkus-dev-files-mvn
    weight: null
status: {}
