apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/part-of: code-with-quarkus-dev-files-mvn
  name: code-with-quarkus-dev-files-mvn
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/antcosta-tenant/code-with-quarkus-dev-files-mvn/code-with-quarkus-dev-files-mvn@sha256:72928676438d843a0c7b4596a114aaaec9ca23cadf3115c5c62b2df26b232ffa
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
