apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-dev-files-mvn
    app.kubernetes.io/part-of: code-with-quarkus-dev-files-mvn
  name: code-with-quarkus-dev-files-mvn
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-quarkus-app
    app.kubernetes.io/instance: code-with-quarkus-dev-files-mvn
status:
  loadBalancer: {}
